/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"go/token"
	"go/types"
	"os"
	"strconv"
	"strings"
	"unsafe"

	"github.com/goplus/gogen"
)

// -----------------------------------------------------------------------------

func fieldIndex(t types.Type, name string) int {
	if struc, ok := t.Underlying().(*types.Struct); ok {
		for i, n := 0, struc.NumFields(); i < n; i++ {
			field := struc.Field(i)
			if field.Name() == name {
				return i
			}
		}
	}
	panic("fieldIndex failed: " + name)
}

type genCtx struct {
	enums         map[string]types.Object
	out           *gogen.Package
	scope         *types.Scope
	strSlice      *types.Slice
	stringEnum    types.Type
	restr         types.Type
	iLimit        int
	iRequired     int
	iOptionalIf   int
	iNotAllowedIf int
	iValues       int
	delays        []func()
}

func gen(ret *pkgRestriction) {
	out := gogen.NewPackage(ret.pkgPath, ret.pkgName, nil)
	xai := out.Import("github.com/goplus/xai/spec")
	str := types.Typ[types.String]
	restr := xai.Ref("Restriction").Type()
	stringEnum := xai.Ref("StringEnum").Type()
	ptrRestr := types.NewPointer(restr)           // *xai.Restriction
	mapNameToRestr := types.NewMap(str, ptrRestr) // map[string]*xai.Restriction
	ctx := &genCtx{
		out:           out,
		scope:         out.Types.Scope(),
		enums:         make(map[string]types.Object),
		strSlice:      types.NewSlice(str),
		stringEnum:    stringEnum,
		restr:         restr,
		iLimit:        fieldIndex(restr, "Limit"),
		iNotAllowedIf: fieldIndex(restr, "NotAllowedIf"),
		iOptionalIf:   fieldIndex(restr, "OptionalIf"),
		iRequired:     fieldIndex(restr, "Required"),
		iValues:       fieldIndex(stringEnum, "Values"),
	}
	for _, r := range ret.types {
		typName := r.typ.Obj().Name()
		name := "restriction_" + typName
		varDefs := out.NewVarDefs(ctx.scope)
		ctx.delays = append(ctx.delays, func() {
			varDefs.NewAndInit(func(cb *gogen.CodeBuilder) int {
				flds := r.fields
				for _, fld := range flds {
					cb.Val(fld.newName)
					genRestriction(ctx, cb, fld)
				}
				cb.MapLit(mapNameToRestr, len(flds)<<1)
				return 1
			}, token.NoPos, nil, name)
		})
	}
	for _, delay := range ctx.delays {
		delay()
	}
	fmt.Println("// Code generated by restrict_gen; DO NOT EDIT.")
	fmt.Println()
	err := out.WriteTo(os.Stdout)
	if err != nil {
		log("genRestriction failed:", err)
		os.Exit(1)
	}
}

func genRestriction(ctx *genCtx, cb *gogen.CodeBuilder, fld *fieldRestriction) {
	n := 0
	if len(fld.stringEnum) > 0 {
		cb.Val(ctx.iLimit)
		genStringEnum(ctx, cb, fld)
		n += 2
	}
	if len(fld.notAllowedIf) > 0 {
		cb.Val(ctx.iNotAllowedIf)
		genStrSlice(ctx, cb, fld.notAllowedIf)
		n += 2
	}
	if len(fld.optionalIf) > 0 {
		cb.Val(ctx.iOptionalIf)
		genStrSlice(ctx, cb, fld.optionalIf)
		n += 2
	}
	if fld.required {
		cb.Val(ctx.iRequired)
		cb.Val(true)
		n += 2
	}
	cb.StructLit(ctx.restr, n, true).UnaryOp(token.AND)
}

func genStrSlice(ctx *genCtx, cb *gogen.CodeBuilder, vals []string) {
	for _, val := range vals {
		cb.Val(val)
	}
	cb.SliceLit(ctx.strSlice, len(vals))
}

func genStringEnum(ctx *genCtx, cb *gogen.CodeBuilder, fld *fieldRestriction) {
	typKey := checksum(fld.stringEnum)
	v, ok := ctx.enums[typKey]
	if !ok {
		scope := ctx.scope
		name := fld.enumSuggName
		if scope.Lookup(name) != nil { // avoid name conflict
			name += strconv.Itoa(scope.Len() + 1)
		}
		ctx.out.NewVarDefs(scope).NewAndInit(func(cb *gogen.CodeBuilder) int {
			vals := fld.stringEnum
			cb.Val(ctx.iValues)
			genStrSlice(ctx, cb, vals)
			cb.StructLit(ctx.stringEnum, 2, true).UnaryOp(token.AND)
			return 1
		}, token.NoPos, nil, name)
		v = scope.Lookup(name)
		ctx.enums[typKey] = v
	}
	cb.Val(v)
}

func checksum(vals []string) string {
	v := strings.Join(vals, "\n")
	hash := sha256.Sum256(unsafe.Slice(unsafe.StringData(v), len(v)))
	return base64.RawStdEncoding.EncodeToString(hash[:])
}

// -----------------------------------------------------------------------------
