// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goplus/xai"
	_ "github.com/goplus/xai/spec/claude"
	_ "github.com/goplus/xai/spec/gemini"
	_ "github.com/goplus/xai/spec/openai"
	"github.com/qiniu/x/errors"
)

const _ = true
//line 01-hello/hello.xgo:10
func main() {
//line 01-hello/hello.xgo:10:1
	ctx := context.Background()
//line 01-hello/hello.xgo:11:1
	ai := func() (_xgo_ret xai.Service) {
//line 01-hello/hello.xgo:11:1
		var _xgo_err error
//line 01-hello/hello.xgo:11:1
		_xgo_ret, _xgo_err = xai.New(ctx, "gemini:xxx")
//line 01-hello/hello.xgo:11:1
		if _xgo_err != nil {
//line 01-hello/hello.xgo:11:1
			_xgo_err = errors.NewFrame(_xgo_err, "xai.new(ctx, \"gemini:xxx\")", "01-hello/hello.xgo", 11, "main.main")
//line 01-hello/hello.xgo:11:1
			panic(_xgo_err)
		}
//line 01-hello/hello.xgo:11:1
		return
	}()
//line 01-hello/hello.xgo:12:1
	resp := func() (_xgo_ret xai.GenResponse) {
//line 01-hello/hello.xgo:12:1
		var _xgo_err error
//line 01-hello/hello.xgo:12:1
		_xgo_ret, _xgo_err = ai.Gen(ctx, ai.GenParams().System("Hi"))
//line 01-hello/hello.xgo:12:1
		if _xgo_err != nil {
//line 01-hello/hello.xgo:12:1
			_xgo_err = errors.NewFrame(_xgo_err, "ai.gen(ctx, system = \"Hi\")", "01-hello/hello.xgo", 12, "main.main")
//line 01-hello/hello.xgo:12:1
			panic(_xgo_err)
		}
//line 01-hello/hello.xgo:12:1
		return
	}()
//line 01-hello/hello.xgo:13:1
	fmt.Println(resp.At(0).Part(0).Text())
}
